vrrp_instance VI_1 {
    state BACKUP                 # This is the backup server
    interface enp6s18            # Change to your interface name
    virtual_router_id 51         # Must be the same as on lb-main
    priority 100                 # Lower priority makes it the backup
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass k3scluster
        }
    virtual_ipaddress {
        192.168.1.254/24          # The floating VIP
    }
}