apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-operator-submitter
  namespace: spark-operator
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications", "sparkapplications/status"]
    verbs: ["create","get","list","watch","delete","patch"]
  - apiGroups: [""]
    resources: ["pods","pods/log","events"]
    verbs: ["get","list","watch","create","delete","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-worker-spark-submitter
  namespace: spark-operator
subjects:
  - kind: ServiceAccount
    name: airflow-worker
    namespace: airflow
roleRef:
  kind: Role
  name: spark-operator-submitter
  apiGroup: rbac.authorization.k8s.io