# history-server-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: history-server-ingress
  namespace: spark-operator
spec:
  ingressClassName: nginx
  rules:
  - host: spark-history.homelab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spark-history-server-svc
            port:
              number: 18080
