FROM python:3.10.12-slim-bookworm AS builder

RUN pip install build twine hatch
COPY . /source
WORKDIR /source
RUN python -m build

FROM tiendat2807/spark-lakehouse:0.0.9

USER root

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install -y gcc python3-dev tini curl && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/*
RUN pip install uv --no-cache-dir

COPY --from=builder /source/dist/*.whl /tmp/
COPY requirements.txt /tmp/

RUN uv pip install --system --no-cache /tmp/*.whl && \
    uv pip install --system --no-cache -r /tmp/requirements.txt && \
    rm -rf /tmp/*.whl /tmp/requirements.txt

RUN useradd -m -s /bin/bash application && \
    mkdir -p /home/application/workspace && \
    chown -R application:application /home/application

USER application

WORKDIR /home/application/workspace

ENTRYPOINT ["tini", "--", "python3", "-m", "jupyterlab", \
    "--ip=0.0.0.0", "--port=8888", "--no-browser", \
    "--allow-root", "--NotebookApp.allow_origin='*'", \
    "--NotebookApp.token='123'"]

EXPOSE 8888