apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "github-events-{{ ds }}-{{ task_instance.try_number }}"
  namespace: spark-operator
spec:
  sparkConf:
    "fs.s3a.access.key": "admin"
    "fs.s3a.secret.key": "password"
    "fs.s3a.endpoint": "http://192.168.1.111:9000"
    "fs.s3a.path.style.access": "true"
    "fs.s3a.connection.ssl.enabled": "false"
    "fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "tiendat2807/spark-lakehouse:0.0.9"
  imagePullPolicy: Always
  mainApplicationFile: "s3a://airflow/dags/staging/github_events.py"
  sparkVersion: "3.5.6"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "1024m"
    labels:
      version: 3.5.6
    serviceAccount: spark-operator-spark
    env:
      - name: AWS_REGION
        value: us-east-1
      - name: AWS_ACCESS_KEY_ID
        value: admin
      - name: AWS_SECRET_ACCESS_KEY
        value: password
      - name: S3_ENDPOINT
        value: 192.168.1.111:9000
      - name: S3_SSL_ENABLE
        value: "false"
      - name: S3_PATH_STYLE_ACCESS
        value: "true"
      - name: S3_WAREHOUSE
        value: "s3a://lakehouse/"
      - name: ICEBERG_REST_CATALOG_URI
        value: "http://192.168.1.111:8181"
      - name: DATA_PATH
        value: "s3a://raw/"
  executor:
    cores: 1
    instances: 3
    memory: "2048m"
    labels:
      version: 3.5.6
    env:
      - name: AWS_REGION
        value: us-east-1
      - name: AWS_ACCESS_KEY_ID
        value: admin
      - name: AWS_SECRET_ACCESS_KEY
        value: password
      - name: S3_ENDPOINT
        value: 192.168.1.111:9000
      - name: S3_SSL_ENABLE
        value: "false"
      - name: S3_PATH_STYLE_ACCESS
        value: "true"
      - name: S3_WAREHOUSE
        value: "s3a://lakehouse/"
      - name: ICEBERG_REST_CATALOG_URI
        value: "http://192.168.1.111:8181"
      - name: DATA_PATH
        value: "s3a://"
  arguments:
    - "{{ data_interval_start.strftime('%Y-%m-%d') }}"
    - "{{ data_interval_start.strftime('%-H') }}"
